version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=projeto_api_web;Username=postgres;Password=postgres
    restart: always 

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: projeto_api_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always  

volumes:
  pgdata: